project:
  type: website
  output-dir: docs

website:
  title: "Anneliese's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - portfolio.qmd
      - walkthrough.qmd
  page-footer: 
    left: "Copyright 2022, Anneliese Forlenza" 
    right: 
      - icon: github
        href: https://github.com/annelieseforlenza

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



