---
title: "Film Analysis Paper"
about:
  template: jolla
---

For my Politics and Film course during my time as a freshman at GW, I wrote a scholarly investigation of surveillance and discipline in the critically-acclaimed film, *The Help*.

This paper analyzes *The Help* and it's interaction with politics and surveillance, bringing in various pieces of previous film analysis literature as backing to the arguments.

------------------------------------------------------------------------

**Mothers and Maids in Mississippi:**

A Scholarly Investigation of Surveillance and Discipline in *The Help*

In many societies, politics submits itself to the private sphere when surveillance and the watchful gaze exerts power over its subject. Further, by the phrase 'private sphere', it is merely the fact that surveillance over the individual is arguably only in their sphere of knowledge, their own internal spaces causing the individual to become disciplined. It can be thought of, also, that this discipline can be indirectly racist. There seems to be no escape from the discriminatory, normalized behavior that is embedded in this gaze. The film The Help reveals this problem. In Jackson, Mississippi circa 1963, recent graduate and aspiring journalist, Skeeter, has intentions of revealing the real lifestyle of African American maids for southern housewives. I will be arguing that the actions of society in the Jim Crow South act as a surveilling gaze and contribute to an internal discipline of the characters seen in the film. This essay will reveal that due to political life in the 1960s Jim Crow era being focused privately, on the individual, and due to the fact that the racist actions of the South embody a watchful gaze and prove to be a surveilling villain, it takes certain characters to act out with strength and resilience to overcome this political problem. With Foucault's reasoning in The Foucault Reader, The Help provides a critique of his arguments by revealing the absence of intentional racial discipline and in combination with Anker's explanation of a racially driven melodrama in Orgies of Feeling, The Help upholds her reality of purposeful racism through the use of melodramatic elements and roles.

Political life in the 1960s Jim Crow era extends all the way into the individual, specifically highlighted in The Help and their personal sphere. Segregation in the South was normal and to be inherently racist was fitting, for most. Throughout the film, looking through a melodramatic lens, it is brought to attention that the black race and in specific, the two main maids, Aibileen and Minny are deemed the villain and the cause of all that is wrong with society. This is clearly highlighted through the actions and reactions of Hilly, the main housewife. For instance, during their ladies luncheon, Hilly refuses to go to the bathroom because Aibileen uses it as well. She explains, "They carry different diseases than we do". Hilly and the rest of her possy claim the role of the victim, when in reality they are the villain. Even clearer and more dramatic is the scene in which Minny desperately expresses her need to use the bathroom due to a dangerous storm outside. Despite Hilly's discontent, Minny uses it anyways and is fired on the spot. These housewives in Jackson represent a clearly racialized society. In her book Orgies of Feeling, author Anker writes about how the roles of the victim and villain can be racialized. She states, "The national identity constructed out of melodrama can thus elide the unequal realms of freedom as they are lived in the daily particulars of American lives marked by economic disempowerment, racialized exploitation, and unequal access to power" (Anker 87). In addition to a discriminatory and therefore problematic setting in The Help, the society extends to the individual and their personal life as well. For instance, this is seen in the life of Aibileen. When she sits down with Skeeter to be interviewed for the story, she explains how this lifestyle and being a black woman in Mississippi caused the death of her son. Aibileen remarks, "Anniversary of his death: Every year I can't breathe. But to y'all it's just another day of bridge. If you stop \[writing\] this, everything he was gonna die with him". The gaze roots itself within the individual on a personal level, affecting their actions and emotions, as seen in the film. Similarly, the majority of the scenes from The Help are located in households: bedrooms, kitchens, backyards, and dining rooms. Furthermore, this deliberacy could arguably be a reflection of the notion of racism in the private sphere of individuals. This metaphorical aspect of the film enhances the point to its full capacity. The household setting is meant to direct the gaze and surveillance into the characters' personal lives.

With the notion that in The Help, politics are indirectly forced upon individuals and their private lives, it can be advanced further to point out that the discriminatory and normalized actions in Mississippi embody a watchful gaze that disciplines it's subjects. In his book, The Foucault Reader, philosopher Michael Foucault posits, "Disciplinary power, on the other hand, is exercised through its invisibility; at the same time it imposes on those whom it subjects a principle of compulsory visibility... Their visibility assures the hold of the power that is exercised over them (Foucault 199). Often times, the subjects aren't aware that the gaze and therefore discipline is even there. It becomes "normalized". This is true in The Help through the behavior of Hilly and the other wives. However, Foucault's reasoning can be critiqued in so far that he excludes the role that racism and discrimination can play in this scenario. He writes, "The perpetual penalty that traverses all points and supervises every instant in the disciplinary institutions compares, differentiates, hierarchizes, homogenizes, excludes. In short, it normalizes" (195). On the one hand, Foucault's thought is synonymous with the film. But, on the other hand, he disregards the fact that the differentiation, hierarchy, and exclusion can have negative connotations and implications as seen in the film. Moreover, the dominating, overseeing gaze is problematic when it gets to be controlled by racist masses that inherently discipline its \[white\] subjects to think in a discriminatory way. Also, it becomes problematic when it disciplines it's black subjects to think that they are always inferior to the white race. Perhaps Foucault was sincerely not aware and therefore didn't mention race's role in his argument. But, for the sake of this paper, it is important to highlight its importance and problematic implications. The film makes it very clear that this type of discipline infests itself in its variety of subjects. For instance, as Minny and her daughter walk to work, she lists off everything she must do as a young maid. Minny exclaims, "You cooking white food? You taste it with a different spoon. When you serving white folks coffee, put it down in front of them, don't hand it to them cause your hands can't touch". It is the power of the society that is causing Minny to think and act in this way. As Foucault puts it, "In short, this power is exercised rather than possessed; it is not the "priviledge," acquired or preserved, of the dominant class, but the overall effect of its strategic positions--an effect that is manifested and sometimes extended by the position of those who are dominated" (174). Another prime example in the film that displays this type of discipline reversely is in the scene in which Hilly's maid, Yule Mae politely asks Hilly and her husband to help cover a small part of tuition for her son. She explains she would take more pay as a loan and work it off overtime. Immediately after asking, Hilly's husband says as he fakes to check his watch, "I am late. I gotta get going" and leaves the house. Afterwards, Hilly denies Yule the money and blames it on her being a "good Christian". In theory, it is the same watchful force exerting power over both Hilly and Minny in these situations but they are under different disciplines under a racist lens. Nonetheless, these two types are extremely prevalent in The Help and cause a large, ethical problem.

Foucault states, "But the body is also directly involved in a political field; power relations have an immediate hold upon it; they invest it, mark it, train it, torture it... to emit signs" (Foucault 173). Arguably, this power exerts itself on racialized subjects. In response to a racially flawed gaze and power, certain people, arguably coined 'heros' stand out and act against the inherent discipline to follow the norm. Anker argues that melodrama often combines the victim with the hero. And although the roles of the victim, villain, and hero are switched around, this phenomenon is reflected in the ending scene of the film. In the end, the story makes the audience feel as though Aibileen, Minny, and Skeeter are originally victimized but in the end, are meant to be seen as heroes, defeating the racism in their own respects. For one, Skeeter embodies the "outcast" in the film as she is consciously aware of the blatant racism going on in her midst. Moreover, she is seemingly the only one who recognizes it. This gives her willingness to write a book on all of the maid's experiences, the good and the bad. She compiles all of them in a book title The Help. Skeeter must be pointed out as a hero of the film due to her bravery to publish something so taboo for its time. An example of this is in the luncheon scene. Hilly is explaining how there must be a separate bathroom for the colored help. The film angles of this scene in particular and the expressions of Skeeter reveals her growing discontent with this society. As a response, Skeeter answers, "Maybe we should just build you a bathroom outside". Skeeter also reveals her unique and arguably heroic personality when she explains to Aibileen and Minny the purpose of her writing The Help. She says, "I want to show her perspective, so people might understand what it's like from your side". Perhaps Skeeter's background of having a maid, Constantine, who assumed the role of her mother contributes to the motivations of her character. But, nonetheless, Skeeter exemplifies a hero in The Help and confirms Anker's expression of melodramatic roles. Additionally, in the closing scene, Aibileen returns to her white family and finds Hilly accusing her of stealing pieces of silver. Though she didn't touch it, Hilly and Elizabeth (mother that Aibileen works for) place the blame on her and she is unjustly fired on the spot with threats of calling the police. Aibileen works up the nerve to stand up for herself against Hilly. Angrily yet powerful, she says, "All you do is scare and lie to get what you want. You're a godless woman. Ain't you tired Miss Hilly?". Aibileen's character represents someone willing to stand up against the racist masses, led by Hilly in the film. In this scene, she is solving this political problem of racially driven surveillance and discipline and the consequential inequality and violence that comes with it. The film ends with her walking away from her white family. She quotes, "No one had ever asked me what it feels like to be me. Once I told the truth about that, I felt free". Aibileen demonstrates a victim turned hero; a hero for herself and for every person who has been in the situation she had been in; a hero that society needed, even though it believed otherwise. Perhaps breaking free to regain the political power that was once taken away or arguably never given, is the way in which people solve this problem both personally and socially.

In conclusion, the goal of this essay was to reveal the problem that political power is often exerted on subjects in the private sphere and in many instances, pose racist sexist threats to their selective subjects specifically seen in The Help. Furthermore, the power is often exerted by a 'watchful gaze', known as society of the Jim Crow South as its subjects are surveilled through a racist lens and in turn, creates an inherent discipline within the people. Power exerted through the private sphere simply refers to the gaze over an individual's personal lives. This creates a problem that can be arguably solved/responded to by the right subject. And, in the case of The Help, it is with the actions of Skeeter, Minny, and Aibileen on the discrimination in Jackson, Mississppi circa 1963. Through highlighting Anker's argument of race in melodrama as well as critiquing Foucault's idea of surveillance and discipline, these three components of the overall political problem are brought together in partnership with The Help.
