---
title: "My Portfolio"
about:
  template: jolla
  links:
    - icon: Howard Schneider Serves As Wise Voice For Fake News Phenomena
      text: Howard Schneider Serves As Wise Voice For Fake News Phenomena
      href: https://docs.google.com/document/d/1RaNN4B9q73RMQ7z2hi6j6FuOlyu_Kq9nwUCEamf3zvo/edit?usp=sharing
    - icon: Turning Waste Into Wonderful
      text: Turning Waste Into Wonderful
      href: https://docs.google.com/document/d/1kmsiElU7BSC0H7fK7U-2jdHZ4JdlyF61hCPz1eZ57AE/edit?usp=sharing
    - text: Gender Wage Gap Legislative Memo
      href: https://docs.google.com/document/d/1x6fT9iemwTAKFx7xbH6-rQa-C1kmx6TCjnsYb8cTTNU/edit
---

My Work

"Howard Schneider Serves As Wise Voice For Fake News Phenomena" is an article featuring the Executive Director of the Center for News Literacy and a nationally-known expert on political communication in this era of fake news and misinformation. Read more to hear Schneider's stance on misinformation in this modern age.

"Turning Waste Into Wonderful" is a science essay featuring Cuban costume designer, Celia Ledon, and her installation called The Shape of Water which aims to spread awareness about plastic waste. Her work will be on display at The Kennedy Center's RiverRun Festival in April 2023. Read more to hear how GW students are involved in this effort.

The final piece is a Legislative Memo written to Representative Josh Gottheimer (D-NJ) detailing the pressing issue surrounding the gender wage gap, gender parity, and overall women’s rights in the workplace. Read more to learn about my recommendations to the Congressman and the House of Representatives.